name: publish

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  id-token: write

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Extract version from tag
        id: get_version
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          echo "version=${tag#v}" >> "$GITHUB_OUTPUT"

      - name: Update version files
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          echo "Updating version to $VERSION"

          # Update pyproject.toml
          sed -i "s/^version = \".*\"/version = \"${VERSION}\"/" pyproject.toml

          # Update src/nu_waves/version.py
          sed -i "s/^__version__ = \".*\"/__version__ = \"${VERSION}\"/" src/nu_waves/version.py

      - name: Commit version bump to main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout main
          git add pyproject.toml src/nu_waves/version.py
          git commit -m "Bump version to ${{ steps.get_version.outputs.version }}"
          git push origin main

      - name: Check version
        run: |
          grep version pyproject.toml
          grep __version__ src/nu_waves/version.py

      - name: Build package
        run: |
          python -m pip install -U build
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
